BEGIN;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM destination_aliases WHERE normalized_alias IS NULL LIMIT 1
  ) THEN
    RAISE EXCEPTION
      'ABORT Step 1: destination_aliases.normalized_alias contains NULL values. '
      'Populate the column before enforcing NOT NULL.';
  END IF;
  RAISE NOTICE 'Pre-condition OK: no NULLs in destination_aliases.normalized_alias';
END;
$$;

CREATE TABLE IF NOT EXISTS destinations (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              TEXT,
  parent_id         INTEGER REFERENCES destinations(id) ON DELETE SET NULL,
  level             INTEGER NOT NULL DEFAULT 2,
  name              TEXT NOT NULL,
  country_code      VARCHAR(3),
  dial_prefix       TEXT,
  operator_name     TEXT,
  sort_order        INTEGER NOT NULL DEFAULT 0,
  notes             TEXT,
  blocked_reason    TEXT,
  lifecycle_state   TEXT NOT NULL DEFAULT 'draft'
                    CHECK (lifecycle_state IN (
                      'draft', 'pending_review', 'approved',
                      'active', 'suspended', 'blocked', 'retired'
                    )),
  commercial_status TEXT NOT NULL DEFAULT 'pending'
                    CHECK (commercial_status IN ('pending', 'approved', 'blocked')),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by        TEXT,
  updated_by        TEXT,
  approved_by       TEXT,
  approved_at       TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_destinations_code         ON destinations (code);
CREATE INDEX IF NOT EXISTS idx_destinations_level               ON destinations (level);
CREATE INDEX IF NOT EXISTS idx_destinations_country_code        ON destinations (country_code);
CREATE INDEX IF NOT EXISTS idx_destinations_dial_prefix         ON destinations (dial_prefix);
CREATE INDEX IF NOT EXISTS idx_destinations_lifecycle           ON destinations (lifecycle_state);
CREATE INDEX IF NOT EXISTS idx_destinations_commercial          ON destinations (commercial_status);
CREATE INDEX IF NOT EXISTS idx_destinations_parent              ON destinations (parent_id);

DO $$
DECLARE col_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO col_count
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'destinations';
  IF col_count < 15 THEN
    RAISE EXCEPTION
      'Schema guard failed: destinations has % columns, expected >= 15. '
      'An incompatible pre-existing table may have been reused.', col_count;
  END IF;
  RAISE NOTICE 'Schema guard OK: destinations has % columns', col_count;
END;
$$;

CREATE TABLE IF NOT EXISTS destination_groups (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  parent_id   INTEGER REFERENCES destination_groups(id) ON DELETE SET NULL,
  level       INTEGER NOT NULL DEFAULT 1,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS destination_group_members (
  group_id       INTEGER NOT NULL REFERENCES destination_groups(id) ON DELETE CASCADE,
  destination_id INTEGER NOT NULL REFERENCES destinations(id) ON DELETE CASCADE,
  added_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  added_by       TEXT,
  PRIMARY KEY (group_id, destination_id)
);

CREATE INDEX IF NOT EXISTS idx_dgm_destination
    ON destination_group_members (destination_id);

CREATE TABLE IF NOT EXISTS destination_health (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destination_id   INTEGER REFERENCES destinations(id) ON DELETE SET NULL,
  asr_24h          NUMERIC(5,2),
  acd_24h          NUMERIC(8,2),
  call_volume_24h  INTEGER,
  health_score     NUMERIC(5,2),
  status           TEXT NOT NULL DEFAULT 'unknown'
                   CHECK (status IN ('healthy', 'degraded', 'critical', 'unknown')),
  computed_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (destination_id)
);

CREATE INDEX IF NOT EXISTS idx_destination_health_status ON destination_health (status);
CREATE INDEX IF NOT EXISTS idx_destination_health_score  ON destination_health (health_score);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM destination_aliases WHERE normalized_alias IS NULL LIMIT 1
  ) THEN
    RAISE EXCEPTION 'ABORT: destination_aliases.normalized_alias has NULLs.';
  END IF;
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'destination_aliases'
      AND column_name = 'normalized_alias' AND is_nullable = 'YES'
  ) THEN
    ALTER TABLE destination_aliases ALTER COLUMN normalized_alias SET NOT NULL;
    RAISE NOTICE 'destination_aliases.normalized_alias SET NOT NULL applied.';
  ELSE
    RAISE NOTICE 'destination_aliases.normalized_alias already NOT NULL — skipped.';
  END IF;
END;
$$;

COMMIT;

SELECT tablename FROM pg_tables
WHERE schemaname = 'public' AND tablename LIKE 'destination%' ORDER BY tablename;

SELECT COUNT(*) AS destinations_count              FROM destinations;
SELECT COUNT(*) AS destination_groups_count        FROM destination_groups;
SELECT COUNT(*) AS destination_group_members_count FROM destination_group_members;
SELECT COUNT(*) AS destination_health_count        FROM destination_health;

SELECT column_name, is_nullable FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'destination_aliases'
  AND column_name = 'normalized_alias';
