-- 063_countries_reference.sql
--
-- The seeded country reference table 063A requires. Specified in
-- DESTINATION-CATALOGUE-V2.md ("Country identity: a seeded reference table"):
-- country_code is a numbering plan, not a country — 1 is 22 countries, 7 is
-- Russia and Kazakhstan — so country identity must come from outside the
-- catalogue, never be derived from it.
--
-- File numbers vs plan labels: the migration runner requires \d{3}_ filenames,
-- so plan 063A (country identity) will be file 064, and plan 063B (type layer)
-- file 065. This file is the reference data both depend on.
--
-- Provenance — nothing here is typed from memory:
--   · 152 countries extracted from server/country-codes.json (Landline rows),
--     the reference file the application already trusts.
--   · 20 additions enumerated in docs/DESTINATION-HIERARCHY-REPAIR-063.md as
--     known gaps: the NANP Caribbean set plus Barbados, Canada, Jamaica and
--     Kazakhstan.
--   · 6 ITU E.164 global services (iso2 NULL, classification
--     international_service).
-- Netherlands Antilles (ANT) is deliberately ABSENT — deprecated ISO code,
-- flagged in the addendum as needing its own decision.
--
-- dial_code is NOT unique (NANP +1 spans 25 entries here; +7 is two countries).
-- Additive and idempotent: ON CONFLICT DO NOTHING, so a re-run inserts nothing
-- and existing rows are never modified.

BEGIN;

CREATE TABLE IF NOT EXISTS countries (
  id             SERIAL PRIMARY KEY,
  canonical_name VARCHAR(128) NOT NULL,
  iso2           CHAR(2),
  dial_code      VARCHAR(8)  NOT NULL,
  classification VARCHAR(24) NOT NULL CHECK (classification IN ('country','territory','international_service')),
  UNIQUE (canonical_name, dial_code)
);
CREATE UNIQUE INDEX IF NOT EXISTS countries_iso2_idx ON countries (iso2) WHERE iso2 IS NOT NULL;
COMMENT ON TABLE countries IS
  'Seeded reference: ISO 3166 identity + ITU E.164 dial codes. Never derived from the catalogue. The country NODE in destinations is the commercial entity; this table only says what a country is.';

INSERT INTO countries (canonical_name, iso2, dial_code, classification) VALUES
  ('Afghanistan', 'AF', '93', 'country'),
  ('Albania', 'AL', '355', 'country'),
  ('Algeria', 'DZ', '213', 'country'),
  ('American Samoa', 'AS', '1', 'territory'),
  ('Andorra', 'AD', '376', 'country'),
  ('Angola', 'AO', '244', 'country'),
  ('Anguilla', 'AI', '1', 'territory'),
  ('Antigua and Barbuda', 'AG', '1', 'country'),
  ('Argentina', 'AR', '54', 'country'),
  ('Armenia', 'AM', '374', 'country'),
  ('Australia', 'AU', '61', 'country'),
  ('Austria', 'AT', '43', 'country'),
  ('Azerbaijan', 'AZ', '994', 'country'),
  ('Bahamas', 'BS', '1', 'country'),
  ('Bahrain', 'BH', '973', 'country'),
  ('Bangladesh', 'BD', '880', 'country'),
  ('Barbados', 'BB', '1-246', 'country'),
  ('Belarus', 'BY', '375', 'country'),
  ('Belgium', 'BE', '32', 'country'),
  ('Belize', 'BZ', '501', 'country'),
  ('Benin', 'BJ', '229', 'country'),
  ('Bermuda', 'BM', '1', 'territory'),
  ('Bhutan', 'BT', '975', 'country'),
  ('Bolivia', 'BO', '591', 'country'),
  ('Bosnia and Herzegovina', 'BA', '387', 'country'),
  ('Botswana', 'BW', '267', 'country'),
  ('Brazil', 'BR', '55', 'country'),
  ('British Virgin Islands', 'VG', '1', 'territory'),
  ('Bulgaria', 'BG', '359', 'country'),
  ('Burkina Faso', 'BF', '226', 'country'),
  ('Burundi', 'BI', '257', 'country'),
  ('Cambodia', 'KH', '855', 'country'),
  ('Cameroon', 'CM', '237', 'country'),
  ('Canada', 'CA', '1', 'country'),
  ('Cayman Islands', 'KY', '1', 'territory'),
  ('Chile', 'CL', '56', 'country'),
  ('China', 'CN', '86', 'country'),
  ('Colombia', 'CO', '57', 'country'),
  ('Congo DR', 'CD', '243', 'country'),
  ('Costa Rica', 'CR', '506', 'country'),
  ('Croatia', 'HR', '385', 'country'),
  ('Cuba', 'CU', '53', 'country'),
  ('Cyprus', 'CY', '357', 'country'),
  ('Czech Republic', 'CZ', '420', 'country'),
  ('Denmark', 'DK', '45', 'country'),
  ('Dominica', 'DM', '1', 'country'),
  ('Dominican Republic', 'DO', '1', 'country'),
  ('Ecuador', 'EC', '593', 'country'),
  ('Egypt', 'EG', '20', 'country'),
  ('El Salvador', 'SV', '503', 'country'),
  ('Eritrea', 'ER', '291', 'country'),
  ('Estonia', 'EE', '372', 'country'),
  ('Eswatini', 'SZ', '268', 'country'),
  ('Ethiopia', 'ET', '251', 'country'),
  ('Finland', 'FI', '358', 'country'),
  ('France', 'FR', '33', 'country'),
  ('Gambia', 'GM', '220', 'country'),
  ('Georgia', 'GE', '995', 'country'),
  ('Germany', 'DE', '49', 'country'),
  ('Ghana', 'GH', '233', 'country'),
  ('Greece', 'GR', '30', 'country'),
  ('Grenada', 'GD', '1', 'country'),
  ('Guam', 'GU', '1', 'territory'),
  ('Guatemala', 'GT', '502', 'country'),
  ('Guinea', 'GN', '224', 'country'),
  ('Hong Kong', 'HK', '852', 'country'),
  ('Hungary', 'HU', '36', 'country'),
  ('Iceland', 'IS', '354', 'country'),
  ('India', 'IN', '91', 'country'),
  ('Indonesia', 'ID', '62', 'country'),
  ('Iran', 'IR', '98', 'country'),
  ('Iraq', 'IQ', '964', 'country'),
  ('Ireland', 'IE', '353', 'country'),
  ('Israel', 'IL', '972', 'country'),
  ('Italy', 'IT', '39', 'country'),
  ('Jamaica', 'JM', '1-876', 'country'),
  ('Japan', 'JP', '81', 'country'),
  ('Jordan', 'JO', '962', 'country'),
  ('Kazakhstan', 'KZ', '7', 'country'),
  ('Kenya', 'KE', '254', 'country'),
  ('Kuwait', 'KW', '965', 'country'),
  ('Kyrgyzstan', 'KG', '996', 'country'),
  ('Laos', 'LA', '856', 'country'),
  ('Latvia', 'LV', '371', 'country'),
  ('Lebanon', 'LB', '961', 'country'),
  ('Lesotho', 'LS', '266', 'country'),
  ('Liberia', 'LR', '231', 'country'),
  ('Libya', 'LY', '218', 'country'),
  ('Lithuania', 'LT', '370', 'country'),
  ('Luxembourg', 'LU', '352', 'country'),
  ('Madagascar', 'MG', '261', 'country'),
  ('Malawi', 'MW', '265', 'country'),
  ('Malaysia', 'MY', '60', 'country'),
  ('Maldives', 'MV', '960', 'country'),
  ('Mali', 'ML', '223', 'country'),
  ('Malta', 'MT', '356', 'country'),
  ('Mauritius', 'MU', '230', 'country'),
  ('Mexico', 'MX', '52', 'country'),
  ('Moldova', 'MD', '373', 'country'),
  ('Mongolia', 'MN', '976', 'country'),
  ('Montenegro', 'ME', '382', 'country'),
  ('Montserrat', 'MS', '1', 'territory'),
  ('Morocco', 'MA', '212', 'country'),
  ('Mozambique', 'MZ', '258', 'country'),
  ('Myanmar', 'MM', '95', 'country'),
  ('Namibia', 'NA', '264', 'country'),
  ('Nepal', 'NP', '977', 'country'),
  ('Netherlands', 'NL', '31', 'country'),
  ('New Zealand', 'NZ', '64', 'country'),
  ('Nicaragua', 'NI', '505', 'country'),
  ('Niger', 'NE', '227', 'country'),
  ('Nigeria', 'NG', '234', 'country'),
  ('North Korea', 'KP', '850', 'country'),
  ('North Macedonia', 'MK', '389', 'country'),
  ('Northern Mariana Islands', 'MP', '1', 'territory'),
  ('Norway', 'NO', '47', 'country'),
  ('Oman', 'OM', '968', 'country'),
  ('Pakistan', 'PK', '92', 'country'),
  ('Palestine', 'PS', '970', 'country'),
  ('Panama', 'PA', '507', 'country'),
  ('Paraguay', 'PY', '595', 'country'),
  ('Peru', 'PE', '51', 'country'),
  ('Philippines', 'PH', '63', 'country'),
  ('Poland', 'PL', '48', 'country'),
  ('Portugal', 'PT', '351', 'country'),
  ('Puerto Rico', 'PR', '1', 'territory'),
  ('Qatar', 'QA', '974', 'country'),
  ('Romania', 'RO', '40', 'country'),
  ('Russia', 'RU', '7', 'country'),
  ('Rwanda', 'RW', '250', 'country'),
  ('Saint Kitts and Nevis', 'KN', '1', 'country'),
  ('Saint Lucia', 'LC', '1', 'country'),
  ('Saint Vincent and the Grenadines', 'VC', '1', 'country'),
  ('Saudi Arabia', 'SA', '966', 'country'),
  ('Serbia', 'RS', '381', 'country'),
  ('Sierra Leone', 'SL', '232', 'country'),
  ('Singapore', 'SG', '65', 'country'),
  ('Slovakia', 'SK', '421', 'country'),
  ('Slovenia', 'SI', '386', 'country'),
  ('Somalia', 'SO', '252', 'country'),
  ('South Africa', 'ZA', '27', 'country'),
  ('South Korea', 'KR', '82', 'country'),
  ('South Sudan', 'SS', '211', 'country'),
  ('Spain', 'ES', '34', 'country'),
  ('Sri Lanka', 'LK', '94', 'country'),
  ('Sudan', 'SD', '249', 'country'),
  ('Suriname', 'SR', '597', 'country'),
  ('Sweden', 'SE', '46', 'country'),
  ('Switzerland', 'CH', '41', 'country'),
  ('Syria', 'SY', '963', 'country'),
  ('Taiwan', 'TW', '886', 'country'),
  ('Tajikistan', 'TJ', '992', 'country'),
  ('Tanzania', 'TZ', '255', 'country'),
  ('Thailand', 'TH', '66', 'country'),
  ('Trinidad and Tobago', 'TT', '1', 'country'),
  ('Tunisia', 'TN', '216', 'country'),
  ('Turkey', 'TR', '90', 'country'),
  ('Turkmenistan', 'TM', '993', 'country'),
  ('Turks and Caicos Islands', 'TC', '1', 'territory'),
  ('U.S. Virgin Islands', 'VI', '1', 'territory'),
  ('Uganda', 'UG', '256', 'country'),
  ('Ukraine', 'UA', '380', 'country'),
  ('United Arab Emirates', 'AE', '971', 'country'),
  ('United Kingdom', 'GB', '44', 'country'),
  ('United States', 'US', '1', 'country'),
  ('Uruguay', 'UY', '598', 'country'),
  ('Uzbekistan', 'UZ', '998', 'country'),
  ('Venezuela', 'VE', '58', 'country'),
  ('Vietnam', 'VN', '84', 'country'),
  ('Yemen', 'YE', '967', 'country'),
  ('Zambia', 'ZM', '260', 'country'),
  ('Zimbabwe', 'ZW', '263', 'country'),
  ('Inmarsat', NULL, '870', 'international_service'),
  ('Universal Personal Telecommunications', NULL, '878', 'international_service'),
  ('Global Mobile Satellite System', NULL, '881', 'international_service'),
  ('International Networks', NULL, '882', 'international_service'),
  ('International Networks', NULL, '883', 'international_service'),
  ('Telecommunications for Disaster Relief', NULL, '888', 'international_service')
ON CONFLICT (canonical_name, dial_code) DO NOTHING;

DO $$
DECLARE n INTEGER; BEGIN
  SELECT count(*) INTO n FROM countries;
  RAISE NOTICE '063: countries reference holds % row(s) (% countries, % territories, % services).',
    n,
    (SELECT count(*) FROM countries WHERE classification = 'country'),
    (SELECT count(*) FROM countries WHERE classification = 'territory'),
    (SELECT count(*) FROM countries WHERE classification = 'international_service');
END $$;

COMMIT;
