/**
 * finance-readiness.ts — can Finance send this customer an invoice today, and
 * if not, exactly why.
 *
 * WHY THIS EXISTS. For a month the working theory was "the collector is why
 * invoices don't generate". Running the existing per-customer trace on
 * 2026-09-07 said, in one call each: PUSHTOTALK has no tariff, asterisk has
 * no invoice schedule, internal-ptcl was never collected, and 2,941 stored
 * CDRs for one day had produced zero snapshots. Every one of those facts was
 * already computed somewhere on the platform. None of them were in one
 * place, so each took a day to find.
 *
 * This module is the PURE part: given the facts the platform already holds
 * about one customer for one period, derive the six columns Finance reads,
 * the ordered list of blockers, the one action that unblocks first, and the
 * three numbers management asks for. No I/O. The route gathers; this judges.
 *
 * Marks are deliberately four-valued. `none` is "there is nothing here and
 * that is not a fault" — a customer with no traffic in the period has no
 * repository rows, no rating and no snapshots, and is not blocked by any of
 * them. Rendering that as three red crosses would send Finance chasing a
 * problem that does not exist, which is the failure this page replaces.
 */

export type Mark = 'ok' | 'warn' | 'fail' | 'none';

export type BlockerStage =
  | 'config' | 'collection' | 'rating' | 'snapshot' | 'certification' | 'reconciliation' | 'invoice';

export interface Blocker {
  stage: BlockerStage;
  code: string;
  /** Operator-facing. Names the thing to fix. */
  detail: string;
}

export type Action = 'configure' | 'collect' | 'rate' | 'review' | 'generate' | 'done';

/** What the route gathers for one customer. Every field is already computed elsewhere. */
export interface CustomerFacts {
  companyId: number;
  name: string;
  iAccount: number;
  iTariff: number | null;
  invoiceEmail: string | null;
  hasSchedule: boolean;
  coverage: { days: string[]; uncovered: string[]; emptyButCollected: string[] };
  repository: { calls: number; minutes: number; cost: number };
  /** Distinct calls verified / snapshotted for THIS account in the period. */
  verified: number;
  snapshotted: number;
  /** Null when there is no tariff to certify against. */
  certification: { state: 'certified' | 'exceptions' | 'uncertified'; reasons: string[] } | null;
  /** Null when the switch's reference has no row for this customer. */
  reconciliation: {
    status: string; referenceAmount: number; platformAmount: number; amountDelta: number;
  } | null;
  invoice: { invoiceNumber: string; status: string } | null;
}

export interface CustomerReadiness {
  companyId: number;
  name: string;
  iAccount: number;
  iTariff: number | null;
  columns: {
    collection: Mark; repository: Mark; rating: Mark;
    snapshots: Mark; reconciliation: Mark; invoice: Mark;
  };
  blockers: Blocker[];
  action: Action;
  /** Every gate passed and configuration is complete — only generation remains, or is done. */
  ready: boolean;
  amounts: { platform: number; reference: number | null };
  invoice: { invoiceNumber: string; status: string } | null;
  counts: { calls: number; verified: number; snapshotted: number; days: number; uncovered: number };
}

const money = (n: number) => `$${n.toFixed(4)}`;

export function assessCustomer(f: CustomerFacts): CustomerReadiness {
  const blockers: Blocker[] = [];
  const { days, uncovered, emptyButCollected } = f.coverage;
  const calls = f.repository.calls;

  // ── Configuration — the fixes that need no engineering at all ───────────
  if (f.iTariff == null) {
    blockers.push({ stage: 'config', code: 'no-tariff',
      detail: 'No tariff on the company record, so calls cannot be priced. Sync it from Sippy (Commercial Mappings) or set it in Rate Manager.' });
  }
  if (!f.invoiceEmail) {
    blockers.push({ stage: 'config', code: 'no-email',
      detail: 'No billing email on the company record. A draft can be generated; it cannot be sent.' });
  }
  if (!f.hasSchedule) {
    blockers.push({ stage: 'config', code: 'no-schedule',
      detail: 'No invoice schedule, so nothing invoices automatically. Drafts can still be generated by hand.' });
  }

  // ── Collection ──────────────────────────────────────────────────────────
  let collection: Mark;
  if (days.length === 0) collection = 'none';
  else if (uncovered.length === 0) collection = 'ok';
  else {
    collection = uncovered.length < days.length ? 'warn' : 'fail';
    blockers.push({ stage: 'collection', code: 'days-uncollected',
      detail: `${uncovered.length} of ${days.length} day(s) never collected: ${uncovered.join(', ')}. Collect them once; everything after runs from the repository.` });
  }

  // ── Repository ──────────────────────────────────────────────────────────
  // A legitimate zero is a collected period with no calls — the switch had
  // none. That is `none`, not a fault. Zero rows on an uncollected period is
  // already a collection blocker; do not report it twice.
  const noTraffic = calls === 0 && uncovered.length === 0 && days.length > 0
    && emptyButCollected.length === days.length;
  const repository: Mark = calls > 0 ? (uncovered.length ? 'warn' : 'ok')
    : noTraffic ? 'none' : (days.length === 0 ? 'none' : 'fail');

  // ── Rating and snapshots — the stage that lost a day on 2026-09-02 ──────
  let rating: Mark, snapshots: Mark;
  if (f.iTariff == null) {
    rating = calls > 0 ? 'fail' : 'none';
    snapshots = calls > 0 ? 'fail' : 'none';
  } else if (calls === 0) {
    rating = 'none'; snapshots = 'none';
  } else {
    rating = f.verified >= calls ? 'ok' : f.verified > 0 ? 'warn' : 'fail';
    if (rating !== 'ok') {
      blockers.push({ stage: 'rating', code: 'rating-pending',
        detail: `${f.verified} of ${calls} stored call(s) verified against tariff ${f.iTariff}. Rate from the repository — no fetch needed.` });
    }
    snapshots = f.verified > 0 && f.snapshotted >= f.verified ? 'ok' : f.snapshotted > 0 ? 'warn' : 'fail';
    if (snapshots !== 'ok') {
      blockers.push({ stage: 'snapshot', code: 'snapshot-pending',
        detail: `${f.snapshotted} of ${f.verified} verified call(s) snapshotted. Invoices are built from snapshots; rating from the repository creates them.` });
    }
  }

  // ── Certification — priced correctly? (only meaningful once rated) ──────
  if (f.certification && calls > 0 && rating === 'ok') {
    if (f.certification.state === 'uncertified') {
      blockers.push({ stage: 'certification', code: 'uncertified',
        detail: f.certification.reasons.join(' ') || 'No verification run stands for this period.' });
    } else if (f.certification.state === 'exceptions') {
      blockers.push({ stage: 'certification', code: 'exceptions',
        detail: `Certification has exceptions: ${f.certification.reasons.join('; ')}. Resolve them, or generate with a recorded override.` });
    }
  }

  // ── Reconciliation — does our total agree with the switch? ──────────────
  let reconciliation: Mark;
  const r = f.reconciliation;
  if (!r) reconciliation = 'none';
  else if (r.status === 'certified') reconciliation = 'ok';
  else if (r.status === 'missing_from_platform') {
    reconciliation = 'fail';
    blockers.push({ stage: 'reconciliation', code: 'missing-from-platform',
      detail: `The switch billed ${money(r.referenceAmount)} and the platform holds nothing for this customer in the period.` });
  } else {
    reconciliation = 'warn';
    blockers.push({ stage: 'reconciliation', code: 'amount-differs',
      detail: `Platform ${money(r.platformAmount)} vs switch ${money(r.referenceAmount)} (${money(r.amountDelta)}). The invoice would not match what the switch charged.` });
  }

  // ── Invoice ─────────────────────────────────────────────────────────────
  const invoice: Mark = f.invoice ? 'ok' : 'fail';
  if (!f.invoice) {
    blockers.push({ stage: 'invoice', code: 'not-generated', detail: 'No draft exists for this period.' });
  }

  // Stage order is the pipeline order, so the first blocker is the one that
  // unblocks first. Configuration outranks everything: it needs no data.
  const order: BlockerStage[] = ['config', 'collection', 'rating', 'snapshot', 'certification', 'reconciliation', 'invoice'];
  blockers.sort((a, b) => order.indexOf(a.stage) - order.indexOf(b.stage));

  const first = blockers[0];
  const action: Action = !first ? 'done'
    : first.stage === 'config' ? 'configure'
    : first.stage === 'collection' ? 'collect'
    : first.stage === 'rating' || first.stage === 'snapshot' ? 'rate'
    : first.stage === 'certification' || first.stage === 'reconciliation' ? 'review'
    : 'generate';

  // Ready means only generation (or nothing) remains — AND there is
  // something to invoice. A zero-traffic customer is not "ready"; it has
  // nothing to bill.
  const ready = calls > 0 && blockers.every(b => b.stage === 'invoice');

  return {
    companyId: f.companyId, name: f.name, iAccount: f.iAccount, iTariff: f.iTariff,
    columns: { collection, repository, rating, snapshots, reconciliation, invoice },
    blockers, action, ready,
    amounts: { platform: f.repository.cost, reference: r ? r.referenceAmount : null },
    invoice: f.invoice,
    counts: { calls, verified: f.verified, snapshotted: f.snapshotted, days: days.length, uncovered: uncovered.length },
  };
}

export interface ReadinessSummary {
  customersReady: number;
  customersTotal: number;
  /** Σ platform cost of READY customers — what could be invoiced now. */
  revenueReady: number;
  /** Σ the switch's reference for every customer it lists — what the week is worth. */
  revenueReference: number;
  /** Days with at least one customer collected, over the period's days. */
  coverageDays: number;
  periodDays: number;
  headline: string;
}

export function summariseReadiness(
  rows: readonly CustomerReadiness[],
  periodDays: readonly string[],
  coverageByCustomer: ReadonlyMap<number, { days: string[]; uncovered: string[] }>,
): ReadinessSummary {
  const ready = rows.filter(r => r.ready);
  const collected = new Set<string>();
  for (const c of coverageByCustomer.values()) {
    const un = new Set(c.uncovered);
    for (const d of c.days) if (!un.has(d)) collected.add(d);
  }
  const revenueReady     = round(ready.reduce((s, r) => s + r.amounts.platform, 0));
  const revenueReference = round(rows.reduce((s, r) => s + (r.amounts.reference ?? 0), 0));
  const coverageDays = periodDays.filter(d => collected.has(d)).length;
  return {
    customersReady: ready.length, customersTotal: rows.length,
    revenueReady, revenueReference,
    coverageDays, periodDays: periodDays.length,
    headline: ready.length === 0
      ? `No customer can be invoiced today. ${revenueReference > 0 ? `The switch billed $${revenueReference.toFixed(2)} for the period.` : ''}`.trim()
      : `${ready.length} of ${rows.length} customer(s) ready — $${revenueReady.toFixed(2)} of $${revenueReference.toFixed(2)}.`,
  };
}

const round = (n: number) => Math.round(n * 1e6) / 1e6;
