// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-redesign/BusinessIntel.tsx": () => import("../components/mockups/dashboard-redesign/BusinessIntel.tsx"),
  "./components/mockups/dashboard-redesign/Diagnostics.tsx": () => import("../components/mockups/dashboard-redesign/Diagnostics.tsx"),
  "./components/mockups/dashboard-redesign/NocCore.tsx": () => import("../components/mockups/dashboard-redesign/NocCore.tsx")
};
